### ISSUE TITLE
Add License and CoC

### ISSUE THREAD

**Issue by mezotv** [dpaulos6/http-status-utils#6]
I think it would be cool if there was a license and code of conduct to make it easier for people to contribute and use this for their own work.

**Comment by dpaulos6** [comment]
Closing as fixed in [a161085](https://github.com/dpaulos6/http-status-utils/commit/a1610854a4cfd474b5be799a0ef1a6e081edb8be) and [dc31f07](https://github.com/dpaulos6/http-status-utils/commit/dc31f07dfd669604fb1e946f6898bbcf77d34718).
